"""add users, invites, trucks, truck_steps, audit_logs

Revision ID: 0b381e5c7e7d
Revises: c859aa8b8281
Create Date: 2026-09-22 14:12:12.958980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b381e5c7e7d'
down_revision: Union[str, None] = 'c859aa8b8281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('worker', 'qc', 'admin', name='invite_role'), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.BigInteger(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.create_index(op.f('ix_invites_expires_at'), 'invites', ['expires_at'], unique=False)
    op.create_index(op.f('ix_invites_is_used'), 'invites', ['is_used'], unique=False)
    op.create_table('trucks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', name='truck_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trucks_current_step'), 'trucks', ['current_step'], unique=False)
    op.create_index(op.f('ix_trucks_serial_number'), 'trucks', ['serial_number'], unique=True)
    op.create_index(op.f('ix_trucks_status'), 'trucks', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('worker', 'qc', 'admin', name='user_role'), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_step_number'), 'users', ['step_number'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('truck_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('qc_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_review', 'approved', 'rejected', name='step_status'), nullable=False),
    sa.Column('media_type', sa.Enum('photo', 'video', 'document', name='media_type'), nullable=True),
    sa.Column('media_file_id', sa.String(length=255), nullable=True),
    sa.Column('media_local_path', sa.String(length=512), nullable=True),
    sa.Column('worker_comment', sa.Text(), nullable=True),
    sa.Column('qc_comment', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['qc_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_truck_steps_qc_id'), 'truck_steps', ['qc_id'], unique=False)
    op.create_index(op.f('ix_truck_steps_status'), 'truck_steps', ['status'], unique=False)
    op.create_index(op.f('ix_truck_steps_step_number'), 'truck_steps', ['step_number'], unique=False)
    op.create_index(op.f('ix_truck_steps_truck_id'), 'truck_steps', ['truck_id'], unique=False)
    op.create_index(op.f('ix_truck_steps_worker_id'), 'truck_steps', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_truck_steps_worker_id'), table_name='truck_steps')
    op.drop_index(op.f('ix_truck_steps_truck_id'), table_name='truck_steps')
    op.drop_index(op.f('ix_truck_steps_step_number'), table_name='truck_steps')
    op.drop_index(op.f('ix_truck_steps_status'), table_name='truck_steps')
    op.drop_index(op.f('ix_truck_steps_qc_id'), table_name='truck_steps')
    op.drop_table('truck_steps')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_step_number'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trucks_status'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_serial_number'), table_name='trucks')
    op.drop_index(op.f('ix_trucks_current_step'), table_name='trucks')
    op.drop_table('trucks')
    op.drop_index(op.f('ix_invites_is_used'), table_name='invites')
    op.drop_index(op.f('ix_invites_expires_at'), table_name='invites')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
